#!/bin/bash

# requires ripgrep and fd


# modify this to point to your vault
vaultPath='/path/to/your/vault/'

note=$1
search='\[\[.+?\]\]'
text=$2

cd $vaultPath
note=$(fd "$note.md")

func="rg -o $search $vaultPath/$note" 


resultArr=()

for result in $($func)
do
    resultArr+=($result)
done

noteNames=()
paths=()

for value in "${resultArr[@]}"
do
    newValue=$(echo $value | tr -d '[]')
    newValue=$(echo $newValue | cut -d '#' -f 1 | cut -d '|' -f 1)
    noteNames+=($newValue)
done

for name in "${noteNames[@]}"
do
    path=$(fd "$name.md")
    paths+=($vaultPath/$path)
done

for path in "${paths[@]}"
do
    echo $'\n'$text >> $path
    echo "appended '$text' to $path"
done


